import Head from 'next/head'
import Navbar from '../../components/Navbar'
import Card from '../../components/Card'
import styles from '../../styles/App.module.css'

export default function Product(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <Navbar/>
       <Card title = {props.title} desc = "salut les loulous" price = "50" Image = "https://www.auto-moto.com/wp-content/uploads/sites/9/2021/02/01-peugeot-208-750x410.jpeg" />
      </main>

     

    </div>
  )
}

localStorage.getItem("selected_product");